spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ugdp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    metrics:
      export:
        prometheus:
          enabled: true
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugdp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ugdp
  template:
    metadata:
      labels:
        app: ugdp
    spec:
      containers:
        - name: ugdp
          image: ugdp:latest
          ports:
            - containerPort: 8080



